"""CLAUDE.md renderer.

Generates CLAUDE.md from TemplateContext with sections for project rules,
plugin commands, memory protocol, safety instructions, and auto-triggers.
"""

from up.sync.renderer import ConfigRenderer, TemplateContext

HEADER = "<!-- Generated by UP Platform. Do not edit manually. Run: up sync -->"


class ClaudeMdRenderer(ConfigRenderer):
    """Renders CLAUDE.md for Claude Code."""

    @property
    def filename(self) -> str:
        return "CLAUDE.md"

    def render(self, context: TemplateContext) -> str:
        sections = [HEADER, ""]
        sections.append(f"# {context.project_name or 'Project'}\n")
        sections.append("> AI Instructions for Claude Code\n")

        sections.append(self._quick_start())
        sections.append(self._ai_rules(context))
        sections.append(self._commands_table(context))
        sections.append(self._safety_rules(context))
        sections.append(self._memory_protocol(context))
        sections.append(self._hooks_summary(context))
        sections.append(self._auto_triggers())

        return "\n".join(s for s in sections if s)

    def _quick_start(self) -> str:
        return (
            "## Quick Start\n\n"
            "1. Read this file for project rules and conventions\n"
            "2. Follow safety rules strictly\n"
            "3. Use listed commands for common tasks\n"
        )

    def _ai_rules(self, ctx: TemplateContext) -> str:
        if not ctx.ai_rules:
            return ""
        lines = ["## AI Rules\n"]
        for rule in ctx.ai_rules:
            lines.append(f"- {rule}")
        lines.append("")
        return "\n".join(lines)

    def _commands_table(self, ctx: TemplateContext) -> str:
        if not ctx.commands:
            return ""
        lines = [
            "## Commands\n",
            "| Command | Description | Plugin |",
            "|---------|-------------|--------|",
        ]
        for cmd in ctx.commands:
            lines.append(f"| `{cmd.name}` | {cmd.description} | {cmd.plugin} |")
        lines.append("")
        return "\n".join(lines)

    def _safety_rules(self, ctx: TemplateContext) -> str:
        if not ctx.safety_rules:
            return ""
        lines = ["## Safety Rules\n"]
        for rule in ctx.safety_rules:
            lines.append(f"- {rule}")
        lines.append("")
        return "\n".join(lines)

    def _memory_protocol(self, ctx: TemplateContext) -> str:
        if not ctx.memory_protocol:
            return ""
        return (
            "## Memory Protocol\n\n"
            "Memory auto-sync is enabled. The system will:\n"
            "- Auto-index commits to memory\n"
            "- Record task completions and errors\n"
            "- Search memory for relevant context before tasks\n"
        )

    def _hooks_summary(self, ctx: TemplateContext) -> str:
        if not ctx.hooks_summary:
            return ""
        lines = ["## Active Hooks\n"]
        for h in ctx.hooks_summary:
            lines.append(f"- **{h.event}** ({h.plugin}): `{h.action}`")
        lines.append("")
        return "\n".join(lines)

    def _auto_triggers(self) -> str:
        return (
            "## Auto-Triggers\n\n"
            "| Trigger | Action |\n"
            "|---------|--------|\n"
            "| Plugin installed/enabled/disabled | Config files re-synced |\n"
            "| `up sync` | All config files regenerated |\n"
            "| `up init` | Initial config generated |\n"
        )
