"""Cursorrules renderer.

Generates .cursorrules from TemplateContext, adapted for Cursor IDE format.
"""

from up.sync.renderer import ConfigRenderer, TemplateContext

HEADER = "# Generated by UP Platform. Do not edit manually."


class CursorrulesRenderer(ConfigRenderer):
    """Renders .cursorrules for Cursor IDE."""

    @property
    def filename(self) -> str:
        return ".cursorrules"

    def render(self, context: TemplateContext) -> str:
        sections = [HEADER, ""]
        sections.append(self._project_overview(context))
        sections.append(self._code_style(context))
        sections.append(self._command_reference(context))
        sections.append(self._safety_rules(context))
        return "\n".join(s for s in sections if s)

    def _project_overview(self, ctx: TemplateContext) -> str:
        name = ctx.project_name or "Project"
        return (
            f"# {name}\n\n"
            "You are an AI assistant working on this project.\n"
            "Follow the rules and conventions below.\n"
        )

    def _code_style(self, ctx: TemplateContext) -> str:
        if not ctx.ai_rules:
            return ""
        lines = ["# Code Style & Rules\n"]
        for rule in ctx.ai_rules:
            lines.append(f"- {rule}")
        lines.append("")
        return "\n".join(lines)

    def _command_reference(self, ctx: TemplateContext) -> str:
        if not ctx.commands:
            return ""
        lines = ["# Available Commands\n"]
        for cmd in ctx.commands:
            lines.append(f"- `{cmd.name}` — {cmd.description} (from {cmd.plugin})")
        lines.append("")
        return "\n".join(lines)

    def _safety_rules(self, ctx: TemplateContext) -> str:
        if not ctx.safety_rules:
            return ""
        lines = ["# Safety Rules\n"]
        for rule in ctx.safety_rules:
            lines.append(f"- {rule}")
        lines.append("")
        return "\n".join(lines)
