"""Tests for sync-config CLI command."""

import json
from pathlib import Path

import pytest

from up.commands.sync_config import run_sync


def _setup_workspace(tmp_path):
    """Create a minimal workspace with config and plugins."""
    up_dir = tmp_path / ".up"
    up_dir.mkdir()

    config = {"project": {"name": "test-app"}, "automation": {"memory": {}}}
    (up_dir / "config.json").write_text(json.dumps(config))

    # Create a builtin plugin
    plugin_dir = up_dir / "plugins" / "builtin" / "safety"
    plugin_dir.mkdir(parents=True)
    (plugin_dir / "plugin.json").write_text(json.dumps({
        "name": "safety",
        "version": "1.0.0",
        "category": "safety",
    }))

    hooks_dir = plugin_dir / "hooks"
    hooks_dir.mkdir()
    (hooks_dir / "hooks.json").write_text(json.dumps({
        "hooks": [{"type": "command", "command": "python check.py", "matcher": "pre_tool_use"}]
    }))

    return tmp_path


class TestRunSync:
    def test_generates_all_files(self, tmp_path):
        ws = _setup_workspace(tmp_path)
        result = run_sync(ws)
        assert result["written"] == 3
        assert (ws / "CLAUDE.md").exists()
        assert (ws / ".cursorrules").exists()
        assert (ws / ".claude" / "settings.json").exists()

    def test_claude_md_content(self, tmp_path):
        ws = _setup_workspace(tmp_path)
        run_sync(ws)
        content = (ws / "CLAUDE.md").read_text()
        assert "Generated by UP Platform" in content
        assert "test-app" in content

    def test_cursorrules_content(self, tmp_path):
        ws = _setup_workspace(tmp_path)
        run_sync(ws)
        content = (ws / ".cursorrules").read_text()
        assert "Generated by UP Platform" in content

    def test_claude_settings_content(self, tmp_path):
        ws = _setup_workspace(tmp_path)
        run_sync(ws)
        data = json.loads((ws / ".claude" / "settings.json").read_text())
        assert "hooks" in data

    def test_dry_run_no_write(self, tmp_path):
        ws = _setup_workspace(tmp_path)
        result = run_sync(ws, dry_run=True)
        assert result["written"] == 3
        assert not (ws / "CLAUDE.md").exists()

    def test_target_filter(self, tmp_path):
        ws = _setup_workspace(tmp_path)
        result = run_sync(ws, targets=["claude-md"])
        assert result["written"] == 1
        assert (ws / "CLAUDE.md").exists()
        assert not (ws / ".cursorrules").exists()

    def test_skips_unchanged(self, tmp_path):
        ws = _setup_workspace(tmp_path)
        run_sync(ws)
        result = run_sync(ws)
        assert result["skipped"] == 3
        assert result["written"] == 0

    def test_reports_plugin_count(self, tmp_path):
        ws = _setup_workspace(tmp_path)
        result = run_sync(ws)
        assert result["plugins"] == 1

    def test_merges_existing_settings(self, tmp_path):
        ws = _setup_workspace(tmp_path)
        claude_dir = ws / ".claude"
        claude_dir.mkdir()
        (claude_dir / "settings.json").write_text(
            json.dumps({"custom": "value"})
        )
        run_sync(ws)
        data = json.loads((claude_dir / "settings.json").read_text())
        assert data["custom"] == "value"
        assert "hooks" in data
