"""Learn system templates."""

from datetime import date
from pathlib import Path


def create_learn_system(target_dir: Path, ai_target: str, force: bool = False) -> None:
    """Create the learn system structure."""
    # Determine skill directory based on AI target
    if ai_target in ("claude", "both"):
        skill_dir = target_dir / ".claude/skills/learning-system"
    else:
        skill_dir = target_dir / ".cursor/skills/learning-system"

    # Create directories
    dirs = ["research", "insights"]
    for d in dirs:
        (skill_dir / d).mkdir(parents=True, exist_ok=True)

    # Create files
    _create_skill_md(skill_dir, force)
    _create_sources_json(skill_dir, force)
    _create_patterns_md(skill_dir, force)
    _create_gap_analysis_md(skill_dir, force)
    _create_prd_template(skill_dir, force)


def _write_file(path: Path, content: str, force: bool) -> None:
    """Write file if it doesn't exist or force is True."""
    if path.exists() and not force:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)


def _create_skill_md(skill_dir: Path, force: bool) -> None:
    """Create SKILL.md for learn system."""
    content = """---
name: learn
description: Research and create improvement plans
user-invocable: true
allowed-tools: Read, Write, Bash, WebFetch, WebSearch, Glob, Grep
version: "1.0.0"
min-claude-version: "2024.01"
---

# Learning System

Research best practices from open source projects and blogs, then create actionable improvement plans.

## Workflow

```
RESEARCH → ANALYZE → COMPARE → PLAN → IMPLEMENT
```

## Commands

| Command | Description |
|---------|-------------|
| `/learn auto` | Auto-analyze project and generate insights |
| `/learn research [topic]` | Research a specific topic |
| `/learn file [file_path]` | Learn best practices from a specific file |
| `/learn project [project_path]` | Deeply analyze an external project |
| `/learn analyze` | Analyze all research files |
| `/learn compare` | Compare findings with current code |
| `/learn plan` | Generate improvement PRD |
| `/learn full` | Run complete pipeline |

## Phase 1: RESEARCH

### Default Sources

Read `sources.json` for configured sources. Research from:

**Open Source Projects:**
- semgrep/semgrep - Pattern-based code analysis
- github/codeql - Query-based analysis
- High-quality projects in your tech stack

**Blogs & Documentation:**
- Official documentation for your frameworks
- Engineering blogs from top companies

### Actions

1. For **topics**: Use `WebSearch` to find articles, extract architecture patterns.
2. For **files (`/learn file path/to/file`)**: Read the specific file and extract key concepts, patterns, best practices, and implementation ideas.
3. For **projects (`/learn project path/to/project`)**: Deeply analyze the target project repository, extract overall system design, component organization, and error handling strategies.
4. Note innovative approaches and actionable recommendations.

### Output

Save findings to `research/YYYY-MM-DD-topic.md`:

```markdown
# Research: [Topic Name]

**Created**: YYYY-MM-DD
**Status**: 📋 Reference
**Source**: [Project/Blog Name]

---

## Key Findings

1. Finding 1
2. Finding 2

## Applicable Patterns

- Pattern A: Description
- Pattern B: Description

## Code Examples

```language
// example code
```
```

---

## Phase 2: ANALYZE

Read all research files and extract:

1. **Design Patterns** - Architectural approaches
2. **Key Innovations** - Novel techniques
3. **Best Practices** - Industry standards
4. **Reusable Components** - Code/concepts to adopt

### Output

Update `insights/patterns.md` with extracted patterns.

---

## Phase 3: COMPARE

Compare insights with current implementation:

1. Read project's main documentation (CLAUDE.md, README.md)
2. Scan source code for current patterns
3. Identify gaps and opportunities

### Output

Update `insights/gap-analysis.md` with findings.

---

## Phase 4: PLAN

Create improvement plan as PRD:

1. Prioritize gaps by impact/effort
2. Create user stories with acceptance criteria
3. Order by dependencies
4. Save as `prd.json`

### PRD Schema

```json
{
  "project": "Project Name",
  "branchName": "feature/improvements",
  "description": "Brief description",
  "userStories": [
    {
      "id": "US-001",
      "title": "Story title",
      "description": "Description",
      "acceptanceCriteria": ["Criterion 1", "Criterion 2"],
      "priority": 1,
      "effort": "low|medium|high",
      "passes": false
    }
  ]
}
```

---

## Phase 5: IMPLEMENT

Hand off to Product Loop:

```
/product-loop
```

The product loop will:
1. Read `prd.json` generated by learning system
2. Execute tasks with circuit breaker protection
3. Checkpoint before risky changes
4. Track progress

---

## AUTO Mode

When `/learn auto` is invoked:

1. Scan the codebase to detect technologies and patterns
2. Identify improvement areas automatically
3. Generate research topics based on findings
4. Research each topic (limit: 3 topics)
5. Continue with analyze → compare → plan

### Auto Mode Output

```
Project Profile:
- Languages: Python, TypeScript
- Frameworks: FastAPI, React
- Patterns: Repository Pattern, React Hooks
- Improvements: add-caching, optimize-queries
- Topics: FastAPI caching best practices, React performance
```

---

## State Files

| File | Purpose |
|------|---------|
| `sources.json` | Research sources config |
| `research/*.md` | Raw research notes |
| `insights/patterns.md` | Extracted patterns |
| `insights/gap-analysis.md` | Gap analysis |
| `prd.json` | Generated improvement plan |

---

## Context Budget

This skill is context-aware:
- Estimates token usage before reading files
- Warns when approaching budget limits
- Suggests summarization when needed

Check budget: Read `.claude/context_budget.json`
"""
    _write_file(skill_dir / "SKILL.md", content, force)


def _create_sources_json(skill_dir: Path, force: bool) -> None:
    """Create sources.json config."""
    content = """{
  "version": "1.0",
  "updated": "",
  "projects": [
    {
      "name": "example-project",
      "repo": "owner/repo",
      "category": "reference",
      "topics": ["topic1", "topic2"],
      "docs_url": "https://docs.example.com/"
    }
  ],
  "blogs": [
    {
      "name": "Example Blog",
      "url": "https://blog.example.com/",
      "topics": ["topic1", "topic2"]
    }
  ],
  "research_topics": [
    "Add topics relevant to your project"
  ]
}
"""
    _write_file(skill_dir / "sources.json", content, force)


def _create_patterns_md(skill_dir: Path, force: bool) -> None:
    """Create patterns template."""
    today = date.today().isoformat()
    content = f"""# Extracted Patterns

**Created**: {today}
**Updated**: {today}
**Status**: 🔄 Active

---

## How to Use

Add patterns discovered during research phases.

---

## Pattern Template

### Pattern: [Name]

- **Source**: Project/Blog
- **Category**: Architecture | Design | Performance | Security
- **Description**: What it does
- **Implementation**: How it works
- **Applicability**: How we can use it
- **Trade-offs**: Pros and cons

### Code Example

```language
// Example implementation
```

---

## Patterns

*Add patterns below this line*

---
"""
    _write_file(skill_dir / "insights/patterns.md", content, force)


def _create_gap_analysis_md(skill_dir: Path, force: bool) -> None:
    """Create gap analysis template."""
    today = date.today().isoformat()
    content = f"""# Gap Analysis

**Created**: {today}
**Updated**: {today}
**Status**: 🔄 Active

---

## Summary

| Impact | Count | Description |
|--------|-------|-------------|
| 🔴 High | 0 | Critical gaps |
| 🟡 Medium | 0 | Important gaps |
| 🟢 Low | 0 | Nice-to-have |

---

## Gap Template

### Gap: [Name]

- **Current State**: What we have now
- **Best Practice**: What leading projects do
- **Impact**: 🔴 High | 🟡 Medium | 🟢 Low
- **Effort**: Low | Medium | High
- **Recommendation**: What to do

---

## Identified Gaps

*Add gaps below this line*

---
"""
    _write_file(skill_dir / "insights/gap-analysis.md", content, force)


def _create_prd_template(skill_dir: Path, force: bool) -> None:
    """Create PRD template file."""
    content = """{
  "project": "Project Improvements",
  "branchName": "feature/improvements",
  "description": "Improvements identified by learning system",
  "createdAt": "",
  "userStories": [
    {
      "id": "US-001",
      "title": "Example User Story",
      "description": "As a developer, I want X so that Y",
      "acceptanceCriteria": [
        "Criterion 1",
        "Criterion 2"
      ],
      "priority": 1,
      "effort": "medium",
      "passes": false,
      "notes": ""
    }
  ]
}
"""
    _write_file(skill_dir / "prd_template.json", content, force)
